version: '3.9'

networks:
  app_network:
    driver: bridge

services:
  mongo_database:
    image: 'mongodb'
    networks:
      - app_network
    build:
      context: ./
      dockerfile: ./mongoReplica/Dockerfile
    container_name: 'mongo_database'
    ports:
      - '27017:27017'
